// Code generated by MockGen. DO NOT EDIT.
// Source: metrics_history_repository.go
//
// Generated by this command:
//
//	mockgen -source=metrics_history_repository.go -destination=mocks/metrics_history_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	metrics_history "github.com/thatcatdev/kaimu/backend/internal/db/repositories/metrics_history"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, history *metrics_history.MetricsHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, history)
}

// GetBySprintID mocks base method.
func (m *MockRepository) GetBySprintID(ctx context.Context, sprintID uuid.UUID) ([]*metrics_history.MetricsHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySprintID", ctx, sprintID)
	ret0, _ := ret[0].([]*metrics_history.MetricsHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySprintID indicates an expected call of GetBySprintID.
func (mr *MockRepositoryMockRecorder) GetBySprintID(ctx, sprintID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySprintID", reflect.TypeOf((*MockRepository)(nil).GetBySprintID), ctx, sprintID)
}

// GetBySprintIDAndDateRange mocks base method.
func (m *MockRepository) GetBySprintIDAndDateRange(ctx context.Context, sprintID uuid.UUID, startDate, endDate time.Time) ([]*metrics_history.MetricsHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySprintIDAndDateRange", ctx, sprintID, startDate, endDate)
	ret0, _ := ret[0].([]*metrics_history.MetricsHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySprintIDAndDateRange indicates an expected call of GetBySprintIDAndDateRange.
func (mr *MockRepositoryMockRecorder) GetBySprintIDAndDateRange(ctx, sprintID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySprintIDAndDateRange", reflect.TypeOf((*MockRepository)(nil).GetBySprintIDAndDateRange), ctx, sprintID, startDate, endDate)
}

// GetLatestBySprintID mocks base method.
func (m *MockRepository) GetLatestBySprintID(ctx context.Context, sprintID uuid.UUID) (*metrics_history.MetricsHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBySprintID", ctx, sprintID)
	ret0, _ := ret[0].(*metrics_history.MetricsHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBySprintID indicates an expected call of GetLatestBySprintID.
func (mr *MockRepositoryMockRecorder) GetLatestBySprintID(ctx, sprintID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBySprintID", reflect.TypeOf((*MockRepository)(nil).GetLatestBySprintID), ctx, sprintID)
}

// Upsert mocks base method.
func (m *MockRepository) Upsert(ctx context.Context, history *metrics_history.MetricsHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRepositoryMockRecorder) Upsert(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRepository)(nil).Upsert), ctx, history)
}
