// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/organization_member/organization_member_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/organization_member/organization_member_repository.go -destination=internal/db/repositories/organization_member/mocks/organization_member_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	organization_member "github.com/thatcatdev/pulse-backend/internal/db/repositories/organization_member"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, member *organization_member.OrganizationMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, member)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, orgID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, orgID, userID)
}

// GetByOrgAndUser mocks base method.
func (m *MockRepository) GetByOrgAndUser(ctx context.Context, orgID, userID uuid.UUID) (*organization_member.OrganizationMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgAndUser", ctx, orgID, userID)
	ret0, _ := ret[0].(*organization_member.OrganizationMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrgAndUser indicates an expected call of GetByOrgAndUser.
func (mr *MockRepositoryMockRecorder) GetByOrgAndUser(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgAndUser", reflect.TypeOf((*MockRepository)(nil).GetByOrgAndUser), ctx, orgID, userID)
}

// GetByOrgID mocks base method.
func (m *MockRepository) GetByOrgID(ctx context.Context, orgID uuid.UUID) ([]*organization_member.OrganizationMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgID", ctx, orgID)
	ret0, _ := ret[0].([]*organization_member.OrganizationMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrgID indicates an expected call of GetByOrgID.
func (mr *MockRepositoryMockRecorder) GetByOrgID(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgID", reflect.TypeOf((*MockRepository)(nil).GetByOrgID), ctx, orgID)
}

// GetByUserID mocks base method.
func (m *MockRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*organization_member.OrganizationMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*organization_member.OrganizationMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockRepository)(nil).GetByUserID), ctx, userID)
}
