// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/board_column/board_column_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/board_column/board_column_repository.go -destination=internal/db/repositories/board_column/mocks/board_column_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	board_column "github.com/thatcatdev/kaimu/backend/internal/db/repositories/board_column"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, column *board_column.BoardColumn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, column)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, column any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, column)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// GetByBoardID mocks base method.
func (m *MockRepository) GetByBoardID(ctx context.Context, boardID uuid.UUID) ([]*board_column.BoardColumn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBoardID", ctx, boardID)
	ret0, _ := ret[0].([]*board_column.BoardColumn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBoardID indicates an expected call of GetByBoardID.
func (mr *MockRepositoryMockRecorder) GetByBoardID(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBoardID", reflect.TypeOf((*MockRepository)(nil).GetByBoardID), ctx, boardID)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*board_column.BoardColumn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*board_column.BoardColumn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetMaxPosition mocks base method.
func (m *MockRepository) GetMaxPosition(ctx context.Context, boardID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxPosition", ctx, boardID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxPosition indicates an expected call of GetMaxPosition.
func (mr *MockRepositoryMockRecorder) GetMaxPosition(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxPosition", reflect.TypeOf((*MockRepository)(nil).GetMaxPosition), ctx, boardID)
}

// GetVisibleByBoardID mocks base method.
func (m *MockRepository) GetVisibleByBoardID(ctx context.Context, boardID uuid.UUID) ([]*board_column.BoardColumn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVisibleByBoardID", ctx, boardID)
	ret0, _ := ret[0].([]*board_column.BoardColumn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVisibleByBoardID indicates an expected call of GetVisibleByBoardID.
func (mr *MockRepositoryMockRecorder) GetVisibleByBoardID(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVisibleByBoardID", reflect.TypeOf((*MockRepository)(nil).GetVisibleByBoardID), ctx, boardID)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, column *board_column.BoardColumn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, column)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, column any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, column)
}

// UpdatePositions mocks base method.
func (m *MockRepository) UpdatePositions(ctx context.Context, columns []*board_column.BoardColumn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePositions", ctx, columns)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePositions indicates an expected call of UpdatePositions.
func (mr *MockRepositoryMockRecorder) UpdatePositions(ctx, columns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePositions", reflect.TypeOf((*MockRepository)(nil).UpdatePositions), ctx, columns)
}
