// Code generated by MockGen. DO NOT EDIT.
// Source: invitation_repository.go
//
// Generated by this command:
//
//	mockgen -source=invitation_repository.go -destination=mocks/invitation_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	invitation "github.com/thatcatdev/kaimu/backend/internal/db/repositories/invitation"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, inv *invitation.Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, inv)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// DeleteExpired mocks base method.
func (m *MockRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRepository)(nil).DeleteExpired), ctx)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*invitation.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*invitation.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetByOrgAndEmail mocks base method.
func (m *MockRepository) GetByOrgAndEmail(ctx context.Context, orgID uuid.UUID, email string) (*invitation.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgAndEmail", ctx, orgID, email)
	ret0, _ := ret[0].(*invitation.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrgAndEmail indicates an expected call of GetByOrgAndEmail.
func (mr *MockRepositoryMockRecorder) GetByOrgAndEmail(ctx, orgID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgAndEmail", reflect.TypeOf((*MockRepository)(nil).GetByOrgAndEmail), ctx, orgID, email)
}

// GetByOrgID mocks base method.
func (m *MockRepository) GetByOrgID(ctx context.Context, orgID uuid.UUID) ([]*invitation.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgID", ctx, orgID)
	ret0, _ := ret[0].([]*invitation.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrgID indicates an expected call of GetByOrgID.
func (mr *MockRepositoryMockRecorder) GetByOrgID(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgID", reflect.TypeOf((*MockRepository)(nil).GetByOrgID), ctx, orgID)
}

// GetByToken mocks base method.
func (m *MockRepository) GetByToken(ctx context.Context, token string) (*invitation.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*invitation.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockRepository)(nil).GetByToken), ctx, token)
}

// GetPendingByOrgID mocks base method.
func (m *MockRepository) GetPendingByOrgID(ctx context.Context, orgID uuid.UUID) ([]*invitation.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingByOrgID", ctx, orgID)
	ret0, _ := ret[0].([]*invitation.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingByOrgID indicates an expected call of GetPendingByOrgID.
func (mr *MockRepositoryMockRecorder) GetPendingByOrgID(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingByOrgID", reflect.TypeOf((*MockRepository)(nil).GetPendingByOrgID), ctx, orgID)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, inv *invitation.Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, inv)
}
