// Code generated by MockGen. DO NOT EDIT.
// Source: audit_repository.go
//
// Generated by this command:
//
//	mockgen -source=audit_repository.go -destination=mocks/audit_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	audit "github.com/thatcatdev/kaimu/backend/internal/db/repositories/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, event *audit.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, event)
}

// CreateBatch mocks base method.
func (m *MockRepository) CreateBatch(ctx context.Context, events []*audit.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockRepositoryMockRecorder) CreateBatch(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockRepository)(nil).CreateBatch), ctx, events)
}

// GetByActorID mocks base method.
func (m *MockRepository) GetByActorID(ctx context.Context, actorID uuid.UUID, limit, offset int) ([]*audit.AuditEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByActorID", ctx, actorID, limit, offset)
	ret0, _ := ret[0].([]*audit.AuditEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByActorID indicates an expected call of GetByActorID.
func (mr *MockRepositoryMockRecorder) GetByActorID(ctx, actorID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByActorID", reflect.TypeOf((*MockRepository)(nil).GetByActorID), ctx, actorID, limit, offset)
}

// GetByBoardID mocks base method.
func (m *MockRepository) GetByBoardID(ctx context.Context, boardID uuid.UUID, limit, offset int) ([]*audit.AuditEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBoardID", ctx, boardID, limit, offset)
	ret0, _ := ret[0].([]*audit.AuditEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByBoardID indicates an expected call of GetByBoardID.
func (mr *MockRepositoryMockRecorder) GetByBoardID(ctx, boardID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBoardID", reflect.TypeOf((*MockRepository)(nil).GetByBoardID), ctx, boardID, limit, offset)
}

// GetByEntity mocks base method.
func (m *MockRepository) GetByEntity(ctx context.Context, entityType audit.EntityType, entityID uuid.UUID, limit, offset int) ([]*audit.AuditEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEntity", ctx, entityType, entityID, limit, offset)
	ret0, _ := ret[0].([]*audit.AuditEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByEntity indicates an expected call of GetByEntity.
func (mr *MockRepositoryMockRecorder) GetByEntity(ctx, entityType, entityID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEntity", reflect.TypeOf((*MockRepository)(nil).GetByEntity), ctx, entityType, entityID, limit, offset)
}

// GetByOrganizationID mocks base method.
func (m *MockRepository) GetByOrganizationID(ctx context.Context, orgID uuid.UUID, limit, offset int) ([]*audit.AuditEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganizationID", ctx, orgID, limit, offset)
	ret0, _ := ret[0].([]*audit.AuditEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOrganizationID indicates an expected call of GetByOrganizationID.
func (mr *MockRepositoryMockRecorder) GetByOrganizationID(ctx, orgID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganizationID", reflect.TypeOf((*MockRepository)(nil).GetByOrganizationID), ctx, orgID, limit, offset)
}

// GetByOrganizationIDWithFilters mocks base method.
func (m *MockRepository) GetByOrganizationIDWithFilters(ctx context.Context, orgID uuid.UUID, filters audit.QueryFilters, limit, offset int) ([]*audit.AuditEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganizationIDWithFilters", ctx, orgID, filters, limit, offset)
	ret0, _ := ret[0].([]*audit.AuditEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOrganizationIDWithFilters indicates an expected call of GetByOrganizationIDWithFilters.
func (mr *MockRepositoryMockRecorder) GetByOrganizationIDWithFilters(ctx, orgID, filters, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganizationIDWithFilters", reflect.TypeOf((*MockRepository)(nil).GetByOrganizationIDWithFilters), ctx, orgID, filters, limit, offset)
}

// GetByProjectID mocks base method.
func (m *MockRepository) GetByProjectID(ctx context.Context, projectID uuid.UUID, limit, offset int) ([]*audit.AuditEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectID", ctx, projectID, limit, offset)
	ret0, _ := ret[0].([]*audit.AuditEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByProjectID indicates an expected call of GetByProjectID.
func (mr *MockRepositoryMockRecorder) GetByProjectID(ctx, projectID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectID", reflect.TypeOf((*MockRepository)(nil).GetByProjectID), ctx, projectID, limit, offset)
}

// GetCardMovementsByBoardAndDateRange mocks base method.
func (m *MockRepository) GetCardMovementsByBoardAndDateRange(ctx context.Context, boardID uuid.UUID, startDate, endDate time.Time) ([]*audit.AuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardMovementsByBoardAndDateRange", ctx, boardID, startDate, endDate)
	ret0, _ := ret[0].([]*audit.AuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCardMovementsByBoardAndDateRange indicates an expected call of GetCardMovementsByBoardAndDateRange.
func (mr *MockRepositoryMockRecorder) GetCardMovementsByBoardAndDateRange(ctx, boardID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardMovementsByBoardAndDateRange", reflect.TypeOf((*MockRepository)(nil).GetCardMovementsByBoardAndDateRange), ctx, boardID, startDate, endDate)
}

// GetSprintCardEvents mocks base method.
func (m *MockRepository) GetSprintCardEvents(ctx context.Context, sprintID uuid.UUID, startDate, endDate time.Time) ([]*audit.AuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSprintCardEvents", ctx, sprintID, startDate, endDate)
	ret0, _ := ret[0].([]*audit.AuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSprintCardEvents indicates an expected call of GetSprintCardEvents.
func (mr *MockRepositoryMockRecorder) GetSprintCardEvents(ctx, sprintID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSprintCardEvents", reflect.TypeOf((*MockRepository)(nil).GetSprintCardEvents), ctx, sprintID, startDate, endDate)
}
