// Code generated by MockGen. DO NOT EDIT.
// Source: typesense_client.go
//
// Generated by this command:
//
//	mockgen -source=typesense_client.go -destination=mocks/typesense_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/typesense/typesense-go/v2/typesense/api"
	gomock "go.uber.org/mock/gomock"
)

// MockTypesenseClient is a mock of TypesenseClient interface.
type MockTypesenseClient struct {
	ctrl     *gomock.Controller
	recorder *MockTypesenseClientMockRecorder
	isgomock struct{}
}

// MockTypesenseClientMockRecorder is the mock recorder for MockTypesenseClient.
type MockTypesenseClientMockRecorder struct {
	mock *MockTypesenseClient
}

// NewMockTypesenseClient creates a new mock instance.
func NewMockTypesenseClient(ctrl *gomock.Controller) *MockTypesenseClient {
	mock := &MockTypesenseClient{ctrl: ctrl}
	mock.recorder = &MockTypesenseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTypesenseClient) EXPECT() *MockTypesenseClientMockRecorder {
	return m.recorder
}

// CreateCollection mocks base method.
func (m *MockTypesenseClient) CreateCollection(ctx context.Context, schema *api.CollectionSchema) (*api.CollectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollection", ctx, schema)
	ret0, _ := ret[0].(*api.CollectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCollection indicates an expected call of CreateCollection.
func (mr *MockTypesenseClientMockRecorder) CreateCollection(ctx, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollection", reflect.TypeOf((*MockTypesenseClient)(nil).CreateCollection), ctx, schema)
}

// DeleteDocument mocks base method.
func (m *MockTypesenseClient) DeleteDocument(ctx context.Context, collection, id string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDocument", ctx, collection, id)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDocument indicates an expected call of DeleteDocument.
func (mr *MockTypesenseClientMockRecorder) DeleteDocument(ctx, collection, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDocument", reflect.TypeOf((*MockTypesenseClient)(nil).DeleteDocument), ctx, collection, id)
}

// MultiSearch mocks base method.
func (m *MockTypesenseClient) MultiSearch(ctx context.Context, params *api.MultiSearchParams, searches api.MultiSearchSearchesParameter) (*api.MultiSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiSearch", ctx, params, searches)
	ret0, _ := ret[0].(*api.MultiSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MultiSearch indicates an expected call of MultiSearch.
func (mr *MockTypesenseClientMockRecorder) MultiSearch(ctx, params, searches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiSearch", reflect.TypeOf((*MockTypesenseClient)(nil).MultiSearch), ctx, params, searches)
}

// RetrieveCollection mocks base method.
func (m *MockTypesenseClient) RetrieveCollection(ctx context.Context, name string) (*api.CollectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveCollection", ctx, name)
	ret0, _ := ret[0].(*api.CollectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveCollection indicates an expected call of RetrieveCollection.
func (mr *MockTypesenseClientMockRecorder) RetrieveCollection(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveCollection", reflect.TypeOf((*MockTypesenseClient)(nil).RetrieveCollection), ctx, name)
}

// UpsertDocument mocks base method.
func (m *MockTypesenseClient) UpsertDocument(ctx context.Context, collection string, document any) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDocument", ctx, collection, document)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertDocument indicates an expected call of UpsertDocument.
func (mr *MockTypesenseClientMockRecorder) UpsertDocument(ctx, collection, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDocument", reflect.TypeOf((*MockTypesenseClient)(nil).UpsertDocument), ctx, collection, document)
}
