// Code generated by MockGen. DO NOT EDIT.
// Source: oidc_service.go
//
// Generated by this command:
//
//	mockgen -source=oidc_service.go -destination=mocks/oidc_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	oidc "github.com/thatcatdev/kaimu/backend/internal/services/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAuthorizationURL mocks base method.
func (m *MockService) GetAuthorizationURL(ctx context.Context, providerSlug, redirectURI string) (*oidc.AuthorizationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationURL", ctx, providerSlug, redirectURI)
	ret0, _ := ret[0].(*oidc.AuthorizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizationURL indicates an expected call of GetAuthorizationURL.
func (mr *MockServiceMockRecorder) GetAuthorizationURL(ctx, providerSlug, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationURL", reflect.TypeOf((*MockService)(nil).GetAuthorizationURL), ctx, providerSlug, redirectURI)
}

// GetProviders mocks base method.
func (m *MockService) GetProviders(ctx context.Context) ([]oidc.ProviderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviders", ctx)
	ret0, _ := ret[0].([]oidc.ProviderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviders indicates an expected call of GetProviders.
func (mr *MockServiceMockRecorder) GetProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviders", reflect.TypeOf((*MockService)(nil).GetProviders), ctx)
}

// GetUserIdentities mocks base method.
func (m *MockService) GetUserIdentities(ctx context.Context, userID uuid.UUID) ([]oidc.IdentityInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdentities", ctx, userID)
	ret0, _ := ret[0].([]oidc.IdentityInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIdentities indicates an expected call of GetUserIdentities.
func (mr *MockServiceMockRecorder) GetUserIdentities(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdentities", reflect.TypeOf((*MockService)(nil).GetUserIdentities), ctx, userID)
}

// HandleCallback mocks base method.
func (m *MockService) HandleCallback(ctx context.Context, providerSlug, code, state string) (*oidc.CallbackResult, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, providerSlug, code, state)
	ret0, _ := ret[0].(*oidc.CallbackResult)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockServiceMockRecorder) HandleCallback(ctx, providerSlug, code, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockService)(nil).HandleCallback), ctx, providerSlug, code, state)
}

// UnlinkIdentity mocks base method.
func (m *MockService) UnlinkIdentity(ctx context.Context, userID uuid.UUID, providerSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkIdentity", ctx, userID, providerSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkIdentity indicates an expected call of UnlinkIdentity.
func (mr *MockServiceMockRecorder) UnlinkIdentity(ctx, userID, providerSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkIdentity", reflect.TypeOf((*MockService)(nil).UnlinkIdentity), ctx, userID, providerSlug)
}
