// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type AssignProjectRoleInput struct {
	ProjectID string  `json:"projectId"`
	UserID    string  `json:"userId"`
	RoleID    *string `json:"roleId,omitempty"`
}

type AuditEvent struct {
	ID           string          `json:"id"`
	OccurredAt   time.Time       `json:"occurredAt"`
	Actor        *User           `json:"actor,omitempty"`
	Action       AuditAction     `json:"action"`
	EntityType   AuditEntityType `json:"entityType"`
	EntityID     string          `json:"entityId"`
	Organization *Organization   `json:"organization,omitempty"`
	Project      *Project        `json:"project,omitempty"`
	Board        *Board          `json:"board,omitempty"`
	StateBefore  *string         `json:"stateBefore,omitempty"`
	StateAfter   *string         `json:"stateAfter,omitempty"`
	Metadata     *string         `json:"metadata,omitempty"`
	IPAddress    *string         `json:"ipAddress,omitempty"`
	UserAgent    *string         `json:"userAgent,omitempty"`
	TraceID      *string         `json:"traceId,omitempty"`
}

type AuditEventConnection struct {
	Edges      []*AuditEventEdge `json:"edges"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	TotalCount int               `json:"totalCount"`
}

type AuditEventEdge struct {
	Node   *AuditEvent `json:"node"`
	Cursor string      `json:"cursor"`
}

type AuditFilters struct {
	Actions     []AuditAction     `json:"actions,omitempty"`
	EntityTypes []AuditEntityType `json:"entityTypes,omitempty"`
	ActorID     *string           `json:"actorId,omitempty"`
	StartDate   *time.Time        `json:"startDate,omitempty"`
	EndDate     *time.Time        `json:"endDate,omitempty"`
}

type AuthPayload struct {
	User *User `json:"user"`
}

type Board struct {
	ID           string         `json:"id"`
	Project      *Project       `json:"project"`
	Name         string         `json:"name"`
	Description  *string        `json:"description,omitempty"`
	IsDefault    bool           `json:"isDefault"`
	Columns      []*BoardColumn `json:"columns"`
	Sprints      []*Sprint      `json:"sprints"`
	ActiveSprint *Sprint        `json:"activeSprint,omitempty"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type BoardColumn struct {
	ID        string    `json:"id"`
	Board     *Board    `json:"board"`
	Name      string    `json:"name"`
	Position  int       `json:"position"`
	IsBacklog bool      `json:"isBacklog"`
	IsHidden  bool      `json:"isHidden"`
	IsDone    bool      `json:"isDone"`
	Color     *string   `json:"color,omitempty"`
	WipLimit  *int      `json:"wipLimit,omitempty"`
	Cards     []*Card   `json:"cards"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type BurnDownData struct {
	SprintID   string       `json:"sprintId"`
	SprintName string       `json:"sprintName"`
	StartDate  time.Time    `json:"startDate"`
	EndDate    time.Time    `json:"endDate"`
	IdealLine  []*DataPoint `json:"idealLine"`
	ActualLine []*DataPoint `json:"actualLine"`
}

type BurnUpData struct {
	SprintID   string       `json:"sprintId"`
	SprintName string       `json:"sprintName"`
	StartDate  time.Time    `json:"startDate"`
	EndDate    time.Time    `json:"endDate"`
	ScopeLine  []*DataPoint `json:"scopeLine"`
	DoneLine   []*DataPoint `json:"doneLine"`
}

type Card struct {
	ID          string       `json:"id"`
	Column      *BoardColumn `json:"column"`
	Board       *Board       `json:"board"`
	Sprints     []*Sprint    `json:"sprints"`
	Title       string       `json:"title"`
	Description *string      `json:"description,omitempty"`
	Position    float64      `json:"position"`
	Priority    CardPriority `json:"priority"`
	Assignee    *User        `json:"assignee,omitempty"`
	Tags        []*Tag       `json:"tags"`
	DueDate     *time.Time   `json:"dueDate,omitempty"`
	StoryPoints *int         `json:"storyPoints,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	CreatedBy   *User        `json:"createdBy,omitempty"`
}

type ChangeMemberRoleInput struct {
	UserID string `json:"userId"`
	RoleID string `json:"roleId"`
}

type ColumnFlowData struct {
	ColumnID   string `json:"columnId"`
	ColumnName string `json:"columnName"`
	Color      string `json:"color"`
	Values     []int  `json:"values"`
}

type CreateBoardInput struct {
	ProjectID   string  `json:"projectId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateCardInput struct {
	ColumnID    string        `json:"columnId"`
	Title       string        `json:"title"`
	Description *string       `json:"description,omitempty"`
	Priority    *CardPriority `json:"priority,omitempty"`
	AssigneeID  *string       `json:"assigneeId,omitempty"`
	TagIds      []string      `json:"tagIds,omitempty"`
	DueDate     *time.Time    `json:"dueDate,omitempty"`
	StoryPoints *int          `json:"storyPoints,omitempty"`
}

type CreateColumnInput struct {
	BoardID   string `json:"boardId"`
	Name      string `json:"name"`
	IsBacklog *bool  `json:"isBacklog,omitempty"`
}

type CreateOrganizationInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateProjectInput struct {
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	Key            string  `json:"key"`
	Description    *string `json:"description,omitempty"`
}

type CreateRoleInput struct {
	OrganizationID  string   `json:"organizationId"`
	Name            string   `json:"name"`
	Description     *string  `json:"description,omitempty"`
	PermissionCodes []string `json:"permissionCodes"`
}

type CreateSprintInput struct {
	BoardID   string     `json:"boardId"`
	Name      string     `json:"name"`
	Goal      *string    `json:"goal,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
	EndDate   *time.Time `json:"endDate,omitempty"`
}

type CreateTagInput struct {
	ProjectID   string  `json:"projectId"`
	Name        string  `json:"name"`
	Color       string  `json:"color"`
	Description *string `json:"description,omitempty"`
}

type CumulativeFlowData struct {
	SprintID   string            `json:"sprintId"`
	SprintName string            `json:"sprintName"`
	Columns    []*ColumnFlowData `json:"columns"`
	Dates      []*time.Time      `json:"dates"`
}

type DataPoint struct {
	Date  time.Time `json:"date"`
	Value float64   `json:"value"`
}

type Invitation struct {
	ID           string        `json:"id"`
	Email        string        `json:"email"`
	Token        string        `json:"token"`
	Role         *Role         `json:"role"`
	Organization *Organization `json:"organization"`
	InvitedBy    *User         `json:"invitedBy"`
	ExpiresAt    time.Time     `json:"expiresAt"`
	CreatedAt    time.Time     `json:"createdAt"`
}

type InviteMemberInput struct {
	OrganizationID string `json:"organizationId"`
	Email          string `json:"email"`
	RoleID         string `json:"roleId"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MoveCardInput struct {
	CardID         string  `json:"cardId"`
	TargetColumnID string  `json:"targetColumnId"`
	AfterCardID    *string `json:"afterCardId,omitempty"`
}

type MoveCardToSprintInput struct {
	CardID   string `json:"cardId"`
	SprintID string `json:"sprintId"`
}

type OIDCProvider struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type Organization struct {
	ID          string                `json:"id"`
	Name        string                `json:"name"`
	Slug        string                `json:"slug"`
	Description *string               `json:"description,omitempty"`
	Owner       *User                 `json:"owner"`
	Members     []*OrganizationMember `json:"members"`
	Projects    []*Project            `json:"projects"`
	CreatedAt   time.Time             `json:"createdAt"`
	UpdatedAt   time.Time             `json:"updatedAt"`
}

type OrganizationMember struct {
	ID         string    `json:"id"`
	User       *User     `json:"user"`
	Role       *Role     `json:"role"`
	LegacyRole string    `json:"legacyRole"`
	CreatedAt  time.Time `json:"createdAt"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
	TotalCount      int     `json:"totalCount"`
}

type Permission struct {
	ID           string  `json:"id"`
	Code         string  `json:"code"`
	Name         string  `json:"name"`
	Description  *string `json:"description,omitempty"`
	ResourceType string  `json:"resourceType"`
}

type Project struct {
	ID           string        `json:"id"`
	Organization *Organization `json:"organization"`
	Name         string        `json:"name"`
	Key          string        `json:"key"`
	Description  *string       `json:"description,omitempty"`
	Boards       []*Board      `json:"boards"`
	DefaultBoard *Board        `json:"defaultBoard,omitempty"`
	Tags         []*Tag        `json:"tags"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdatedAt    time.Time     `json:"updatedAt"`
}

type ProjectMember struct {
	ID        string    `json:"id"`
	User      *User     `json:"user"`
	Role      *Role     `json:"role,omitempty"`
	Project   *Project  `json:"project"`
	CreatedAt time.Time `json:"createdAt"`
}

type RefreshTokenPayload struct {
	Success   bool `json:"success"`
	ExpiresIn int  `json:"expiresIn"`
}

type RegisterInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ReorderColumnsInput struct {
	BoardID   string   `json:"boardId"`
	ColumnIds []string `json:"columnIds"`
}

type Role struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description *string       `json:"description,omitempty"`
	IsSystem    bool          `json:"isSystem"`
	Scope       string        `json:"scope"`
	Permissions []*Permission `json:"permissions"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type SearchResult struct {
	Type             SearchEntityType `json:"type"`
	ID               string           `json:"id"`
	Title            string           `json:"title"`
	Description      *string          `json:"description,omitempty"`
	Highlight        string           `json:"highlight"`
	OrganizationID   string           `json:"organizationId"`
	OrganizationName string           `json:"organizationName"`
	ProjectID        *string          `json:"projectId,omitempty"`
	ProjectName      *string          `json:"projectName,omitempty"`
	BoardID          *string          `json:"boardId,omitempty"`
	BoardName        *string          `json:"boardName,omitempty"`
	URL              string           `json:"url"`
	Score            float64          `json:"score"`
}

type SearchResults struct {
	Results    []*SearchResult `json:"results"`
	TotalCount int             `json:"totalCount"`
	Query      string          `json:"query"`
}

type SearchScope struct {
	OrganizationID *string `json:"organizationId,omitempty"`
	ProjectID      *string `json:"projectId,omitempty"`
}

type Sprint struct {
	ID        string       `json:"id"`
	Board     *Board       `json:"board"`
	Name      string       `json:"name"`
	Goal      *string      `json:"goal,omitempty"`
	StartDate *time.Time   `json:"startDate,omitempty"`
	EndDate   *time.Time   `json:"endDate,omitempty"`
	Status    SprintStatus `json:"status"`
	Position  int          `json:"position"`
	Cards     []*Card      `json:"cards"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
	CreatedBy *User        `json:"createdBy,omitempty"`
}

type SprintConnection struct {
	Edges    []*SprintEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type SprintEdge struct {
	Node   *Sprint `json:"node"`
	Cursor string  `json:"cursor"`
}

type SprintStats struct {
	TotalCards           int `json:"totalCards"`
	CompletedCards       int `json:"completedCards"`
	TotalStoryPoints     int `json:"totalStoryPoints"`
	CompletedStoryPoints int `json:"completedStoryPoints"`
	DaysRemaining        int `json:"daysRemaining"`
	DaysElapsed          int `json:"daysElapsed"`
}

type SprintVelocity struct {
	SprintID        string `json:"sprintId"`
	SprintName      string `json:"sprintName"`
	CompletedCards  int    `json:"completedCards"`
	CompletedPoints int    `json:"completedPoints"`
}

type Tag struct {
	ID          string    `json:"id"`
	Project     *Project  `json:"project"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
}

type UpdateBoardInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateCardInput struct {
	ID               string        `json:"id"`
	Title            *string       `json:"title,omitempty"`
	Description      *string       `json:"description,omitempty"`
	Priority         *CardPriority `json:"priority,omitempty"`
	AssigneeID       *string       `json:"assigneeId,omitempty"`
	ClearAssignee    *bool         `json:"clearAssignee,omitempty"`
	TagIds           []string      `json:"tagIds,omitempty"`
	DueDate          *time.Time    `json:"dueDate,omitempty"`
	ClearDueDate     *bool         `json:"clearDueDate,omitempty"`
	StoryPoints      *int          `json:"storyPoints,omitempty"`
	ClearStoryPoints *bool         `json:"clearStoryPoints,omitempty"`
}

type UpdateColumnInput struct {
	ID            string  `json:"id"`
	Name          *string `json:"name,omitempty"`
	Color         *string `json:"color,omitempty"`
	WipLimit      *int    `json:"wipLimit,omitempty"`
	ClearWipLimit *bool   `json:"clearWipLimit,omitempty"`
	IsDone        *bool   `json:"isDone,omitempty"`
}

type UpdateMeInput struct {
	DisplayName *string `json:"displayName,omitempty"`
	Email       *string `json:"email,omitempty"`
}

type UpdateOrganizationInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateProjectInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Key         *string `json:"key,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateRoleInput struct {
	ID              string   `json:"id"`
	Name            *string  `json:"name,omitempty"`
	Description     *string  `json:"description,omitempty"`
	PermissionCodes []string `json:"permissionCodes,omitempty"`
}

type UpdateSprintInput struct {
	Name      *string    `json:"name,omitempty"`
	Goal      *string    `json:"goal,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
	EndDate   *time.Time `json:"endDate,omitempty"`
}

type UpdateTagInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Color       *string `json:"color,omitempty"`
	Description *string `json:"description,omitempty"`
}

type User struct {
	ID            string    `json:"id"`
	Username      string    `json:"username"`
	Email         *string   `json:"email,omitempty"`
	EmailVerified bool      `json:"emailVerified"`
	DisplayName   *string   `json:"displayName,omitempty"`
	AvatarURL     *string   `json:"avatarUrl,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
}

type VelocityData struct {
	Sprints []*SprintVelocity `json:"sprints"`
}

type AuditAction string

const (
	AuditActionCreated                 AuditAction = "CREATED"
	AuditActionUpdated                 AuditAction = "UPDATED"
	AuditActionDeleted                 AuditAction = "DELETED"
	AuditActionCardMoved               AuditAction = "CARD_MOVED"
	AuditActionCardAssigned            AuditAction = "CARD_ASSIGNED"
	AuditActionCardUnassigned          AuditAction = "CARD_UNASSIGNED"
	AuditActionSprintStarted           AuditAction = "SPRINT_STARTED"
	AuditActionSprintCompleted         AuditAction = "SPRINT_COMPLETED"
	AuditActionCardAddedToSprint       AuditAction = "CARD_ADDED_TO_SPRINT"
	AuditActionCardRemovedFromSprint   AuditAction = "CARD_REMOVED_FROM_SPRINT"
	AuditActionMemberInvited           AuditAction = "MEMBER_INVITED"
	AuditActionMemberJoined            AuditAction = "MEMBER_JOINED"
	AuditActionMemberRemoved           AuditAction = "MEMBER_REMOVED"
	AuditActionMemberRoleChanged       AuditAction = "MEMBER_ROLE_CHANGED"
	AuditActionColumnReordered         AuditAction = "COLUMN_REORDERED"
	AuditActionColumnVisibilityToggled AuditAction = "COLUMN_VISIBILITY_TOGGLED"
	AuditActionUserLoggedIn            AuditAction = "USER_LOGGED_IN"
	AuditActionUserLoggedOut           AuditAction = "USER_LOGGED_OUT"
)

var AllAuditAction = []AuditAction{
	AuditActionCreated,
	AuditActionUpdated,
	AuditActionDeleted,
	AuditActionCardMoved,
	AuditActionCardAssigned,
	AuditActionCardUnassigned,
	AuditActionSprintStarted,
	AuditActionSprintCompleted,
	AuditActionCardAddedToSprint,
	AuditActionCardRemovedFromSprint,
	AuditActionMemberInvited,
	AuditActionMemberJoined,
	AuditActionMemberRemoved,
	AuditActionMemberRoleChanged,
	AuditActionColumnReordered,
	AuditActionColumnVisibilityToggled,
	AuditActionUserLoggedIn,
	AuditActionUserLoggedOut,
}

func (e AuditAction) IsValid() bool {
	switch e {
	case AuditActionCreated, AuditActionUpdated, AuditActionDeleted, AuditActionCardMoved, AuditActionCardAssigned, AuditActionCardUnassigned, AuditActionSprintStarted, AuditActionSprintCompleted, AuditActionCardAddedToSprint, AuditActionCardRemovedFromSprint, AuditActionMemberInvited, AuditActionMemberJoined, AuditActionMemberRemoved, AuditActionMemberRoleChanged, AuditActionColumnReordered, AuditActionColumnVisibilityToggled, AuditActionUserLoggedIn, AuditActionUserLoggedOut:
		return true
	}
	return false
}

func (e AuditAction) String() string {
	return string(e)
}

func (e *AuditAction) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuditAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuditAction", str)
	}
	return nil
}

func (e AuditAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type AuditEntityType string

const (
	AuditEntityTypeUser         AuditEntityType = "USER"
	AuditEntityTypeOrganization AuditEntityType = "ORGANIZATION"
	AuditEntityTypeProject      AuditEntityType = "PROJECT"
	AuditEntityTypeBoard        AuditEntityType = "BOARD"
	AuditEntityTypeBoardColumn  AuditEntityType = "BOARD_COLUMN"
	AuditEntityTypeCard         AuditEntityType = "CARD"
	AuditEntityTypeSprint       AuditEntityType = "SPRINT"
	AuditEntityTypeTag          AuditEntityType = "TAG"
	AuditEntityTypeRole         AuditEntityType = "ROLE"
	AuditEntityTypeInvitation   AuditEntityType = "INVITATION"
)

var AllAuditEntityType = []AuditEntityType{
	AuditEntityTypeUser,
	AuditEntityTypeOrganization,
	AuditEntityTypeProject,
	AuditEntityTypeBoard,
	AuditEntityTypeBoardColumn,
	AuditEntityTypeCard,
	AuditEntityTypeSprint,
	AuditEntityTypeTag,
	AuditEntityTypeRole,
	AuditEntityTypeInvitation,
}

func (e AuditEntityType) IsValid() bool {
	switch e {
	case AuditEntityTypeUser, AuditEntityTypeOrganization, AuditEntityTypeProject, AuditEntityTypeBoard, AuditEntityTypeBoardColumn, AuditEntityTypeCard, AuditEntityTypeSprint, AuditEntityTypeTag, AuditEntityTypeRole, AuditEntityTypeInvitation:
		return true
	}
	return false
}

func (e AuditEntityType) String() string {
	return string(e)
}

func (e *AuditEntityType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuditEntityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuditEntityType", str)
	}
	return nil
}

func (e AuditEntityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type CardPriority string

const (
	CardPriorityNone   CardPriority = "NONE"
	CardPriorityLow    CardPriority = "LOW"
	CardPriorityMedium CardPriority = "MEDIUM"
	CardPriorityHigh   CardPriority = "HIGH"
	CardPriorityUrgent CardPriority = "URGENT"
)

var AllCardPriority = []CardPriority{
	CardPriorityNone,
	CardPriorityLow,
	CardPriorityMedium,
	CardPriorityHigh,
	CardPriorityUrgent,
}

func (e CardPriority) IsValid() bool {
	switch e {
	case CardPriorityNone, CardPriorityLow, CardPriorityMedium, CardPriorityHigh, CardPriorityUrgent:
		return true
	}
	return false
}

func (e CardPriority) String() string {
	return string(e)
}

func (e *CardPriority) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CardPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CardPriority", str)
	}
	return nil
}

func (e CardPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MetricMode string

const (
	MetricModeCardCount   MetricMode = "CARD_COUNT"
	MetricModeStoryPoints MetricMode = "STORY_POINTS"
)

var AllMetricMode = []MetricMode{
	MetricModeCardCount,
	MetricModeStoryPoints,
}

func (e MetricMode) IsValid() bool {
	switch e {
	case MetricModeCardCount, MetricModeStoryPoints:
		return true
	}
	return false
}

func (e MetricMode) String() string {
	return string(e)
}

func (e *MetricMode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MetricMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MetricMode", str)
	}
	return nil
}

func (e MetricMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SearchEntityType string

const (
	SearchEntityTypeCard         SearchEntityType = "CARD"
	SearchEntityTypeProject      SearchEntityType = "PROJECT"
	SearchEntityTypeBoard        SearchEntityType = "BOARD"
	SearchEntityTypeOrganization SearchEntityType = "ORGANIZATION"
	SearchEntityTypeUser         SearchEntityType = "USER"
)

var AllSearchEntityType = []SearchEntityType{
	SearchEntityTypeCard,
	SearchEntityTypeProject,
	SearchEntityTypeBoard,
	SearchEntityTypeOrganization,
	SearchEntityTypeUser,
}

func (e SearchEntityType) IsValid() bool {
	switch e {
	case SearchEntityTypeCard, SearchEntityTypeProject, SearchEntityTypeBoard, SearchEntityTypeOrganization, SearchEntityTypeUser:
		return true
	}
	return false
}

func (e SearchEntityType) String() string {
	return string(e)
}

func (e *SearchEntityType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchEntityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchEntityType", str)
	}
	return nil
}

func (e SearchEntityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SprintStatus string

const (
	SprintStatusFuture SprintStatus = "FUTURE"
	SprintStatusActive SprintStatus = "ACTIVE"
	SprintStatusClosed SprintStatus = "CLOSED"
)

var AllSprintStatus = []SprintStatus{
	SprintStatusFuture,
	SprintStatusActive,
	SprintStatusClosed,
}

func (e SprintStatus) IsValid() bool {
	switch e {
	case SprintStatusFuture, SprintStatusActive, SprintStatusClosed:
		return true
	}
	return false
}

func (e SprintStatus) String() string {
	return string(e)
}

func (e *SprintStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SprintStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SprintStatus", str)
	}
	return nil
}

func (e SprintStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
