// Code generated by MockGen. DO NOT EDIT.
// Source: role_permission_repository.go
//
// Generated by this command:
//
//	mockgen -source=role_permission_repository.go -destination=mocks/role_permission_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	permission "github.com/thatcatdev/kaimu/backend/internal/db/repositories/permission"
	role_permission "github.com/thatcatdev/kaimu/backend/internal/db/repositories/role_permission"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, rp *role_permission.RolePermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, rp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, rp)
}

// CreateBatch mocks base method.
func (m *MockRepository) CreateBatch(ctx context.Context, roleID uuid.UUID, permissionIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, roleID, permissionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockRepositoryMockRecorder) CreateBatch(ctx, roleID, permissionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockRepository)(nil).CreateBatch), ctx, roleID, permissionIDs)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, roleID, permissionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, roleID, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, roleID, permissionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, roleID, permissionID)
}

// DeleteByRoleID mocks base method.
func (m *MockRepository) DeleteByRoleID(ctx context.Context, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRoleID", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRoleID indicates an expected call of DeleteByRoleID.
func (mr *MockRepositoryMockRecorder) DeleteByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRoleID", reflect.TypeOf((*MockRepository)(nil).DeleteByRoleID), ctx, roleID)
}

// GetByRoleID mocks base method.
func (m *MockRepository) GetByRoleID(ctx context.Context, roleID uuid.UUID) ([]*role_permission.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]*role_permission.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoleID indicates an expected call of GetByRoleID.
func (mr *MockRepositoryMockRecorder) GetByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoleID", reflect.TypeOf((*MockRepository)(nil).GetByRoleID), ctx, roleID)
}

// GetPermissionCodesByRoleID mocks base method.
func (m *MockRepository) GetPermissionCodesByRoleID(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionCodesByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionCodesByRoleID indicates an expected call of GetPermissionCodesByRoleID.
func (mr *MockRepositoryMockRecorder) GetPermissionCodesByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionCodesByRoleID", reflect.TypeOf((*MockRepository)(nil).GetPermissionCodesByRoleID), ctx, roleID)
}

// GetPermissionsByRoleID mocks base method.
func (m *MockRepository) GetPermissionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]*permission.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]*permission.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsByRoleID indicates an expected call of GetPermissionsByRoleID.
func (mr *MockRepositoryMockRecorder) GetPermissionsByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsByRoleID", reflect.TypeOf((*MockRepository)(nil).GetPermissionsByRoleID), ctx, roleID)
}

// ReplaceForRole mocks base method.
func (m *MockRepository) ReplaceForRole(ctx context.Context, roleID uuid.UUID, permissionIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceForRole", ctx, roleID, permissionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceForRole indicates an expected call of ReplaceForRole.
func (mr *MockRepositoryMockRecorder) ReplaceForRole(ctx, roleID, permissionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceForRole", reflect.TypeOf((*MockRepository)(nil).ReplaceForRole), ctx, roleID, permissionIDs)
}
