// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/card_label/card_label_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/card_label/card_label_repository.go -destination=internal/db/repositories/card_label/mocks/card_label_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	card_label "github.com/thatcatdev/pulse-backend/internal/db/repositories/card_label"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, cardLabel *card_label.CardLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cardLabel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, cardLabel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, cardLabel)
}

// DeleteByCardAndLabel mocks base method.
func (m *MockRepository) DeleteByCardAndLabel(ctx context.Context, cardID, labelID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCardAndLabel", ctx, cardID, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCardAndLabel indicates an expected call of DeleteByCardAndLabel.
func (mr *MockRepositoryMockRecorder) DeleteByCardAndLabel(ctx, cardID, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCardAndLabel", reflect.TypeOf((*MockRepository)(nil).DeleteByCardAndLabel), ctx, cardID, labelID)
}

// DeleteByCardID mocks base method.
func (m *MockRepository) DeleteByCardID(ctx context.Context, cardID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCardID", ctx, cardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCardID indicates an expected call of DeleteByCardID.
func (mr *MockRepositoryMockRecorder) DeleteByCardID(ctx, cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCardID", reflect.TypeOf((*MockRepository)(nil).DeleteByCardID), ctx, cardID)
}

// GetByCardID mocks base method.
func (m *MockRepository) GetByCardID(ctx context.Context, cardID uuid.UUID) ([]*card_label.CardLabel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCardID", ctx, cardID)
	ret0, _ := ret[0].([]*card_label.CardLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCardID indicates an expected call of GetByCardID.
func (mr *MockRepositoryMockRecorder) GetByCardID(ctx, cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCardID", reflect.TypeOf((*MockRepository)(nil).GetByCardID), ctx, cardID)
}

// GetByLabelID mocks base method.
func (m *MockRepository) GetByLabelID(ctx context.Context, labelID uuid.UUID) ([]*card_label.CardLabel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLabelID", ctx, labelID)
	ret0, _ := ret[0].([]*card_label.CardLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLabelID indicates an expected call of GetByLabelID.
func (mr *MockRepositoryMockRecorder) GetByLabelID(ctx, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLabelID", reflect.TypeOf((*MockRepository)(nil).GetByLabelID), ctx, labelID)
}

// SetLabelsForCard mocks base method.
func (m *MockRepository) SetLabelsForCard(ctx context.Context, cardID uuid.UUID, labelIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLabelsForCard", ctx, cardID, labelIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLabelsForCard indicates an expected call of SetLabelsForCard.
func (mr *MockRepositoryMockRecorder) SetLabelsForCard(ctx, cardID, labelIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLabelsForCard", reflect.TypeOf((*MockRepository)(nil).SetLabelsForCard), ctx, cardID, labelIDs)
}
