// Code generated by MockGen. DO NOT EDIT.
// Source: oidc_identity_repository.go
//
// Generated by this command:
//
//	mockgen -source=oidc_identity_repository.go -destination=mocks/oidc_identity_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	oidc_identity "github.com/thatcatdev/kaimu/backend/internal/db/repositories/oidc_identity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, identity *oidc_identity.OIDCIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, identity)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// DeleteByUserIDAndIssuer mocks base method.
func (m *MockRepository) DeleteByUserIDAndIssuer(ctx context.Context, userID uuid.UUID, issuer string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDAndIssuer", ctx, userID, issuer)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIDAndIssuer indicates an expected call of DeleteByUserIDAndIssuer.
func (mr *MockRepositoryMockRecorder) DeleteByUserIDAndIssuer(ctx, userID, issuer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDAndIssuer", reflect.TypeOf((*MockRepository)(nil).DeleteByUserIDAndIssuer), ctx, userID, issuer)
}

// GetByIssuerAndSubject mocks base method.
func (m *MockRepository) GetByIssuerAndSubject(ctx context.Context, issuer, subject string) (*oidc_identity.OIDCIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIssuerAndSubject", ctx, issuer, subject)
	ret0, _ := ret[0].(*oidc_identity.OIDCIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIssuerAndSubject indicates an expected call of GetByIssuerAndSubject.
func (mr *MockRepositoryMockRecorder) GetByIssuerAndSubject(ctx, issuer, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIssuerAndSubject", reflect.TypeOf((*MockRepository)(nil).GetByIssuerAndSubject), ctx, issuer, subject)
}

// GetByUserID mocks base method.
func (m *MockRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*oidc_identity.OIDCIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*oidc_identity.OIDCIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockRepository)(nil).GetByUserID), ctx, userID)
}
