// Code generated by MockGen. DO NOT EDIT.
// Source: card_tag_repository.go
//
// Generated by this command:
//
//	mockgen -source=card_tag_repository.go -destination=mocks/card_tag_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	card_tag "github.com/thatcatdev/kaimu/backend/internal/db/repositories/card_tag"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, cardTag *card_tag.CardTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cardTag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, cardTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, cardTag)
}

// DeleteByCardAndTag mocks base method.
func (m *MockRepository) DeleteByCardAndTag(ctx context.Context, cardID, tagID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCardAndTag", ctx, cardID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCardAndTag indicates an expected call of DeleteByCardAndTag.
func (mr *MockRepositoryMockRecorder) DeleteByCardAndTag(ctx, cardID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCardAndTag", reflect.TypeOf((*MockRepository)(nil).DeleteByCardAndTag), ctx, cardID, tagID)
}

// DeleteByCardID mocks base method.
func (m *MockRepository) DeleteByCardID(ctx context.Context, cardID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCardID", ctx, cardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCardID indicates an expected call of DeleteByCardID.
func (mr *MockRepositoryMockRecorder) DeleteByCardID(ctx, cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCardID", reflect.TypeOf((*MockRepository)(nil).DeleteByCardID), ctx, cardID)
}

// GetByCardID mocks base method.
func (m *MockRepository) GetByCardID(ctx context.Context, cardID uuid.UUID) ([]*card_tag.CardTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCardID", ctx, cardID)
	ret0, _ := ret[0].([]*card_tag.CardTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCardID indicates an expected call of GetByCardID.
func (mr *MockRepositoryMockRecorder) GetByCardID(ctx, cardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCardID", reflect.TypeOf((*MockRepository)(nil).GetByCardID), ctx, cardID)
}

// GetByTagID mocks base method.
func (m *MockRepository) GetByTagID(ctx context.Context, tagID uuid.UUID) ([]*card_tag.CardTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTagID", ctx, tagID)
	ret0, _ := ret[0].([]*card_tag.CardTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTagID indicates an expected call of GetByTagID.
func (mr *MockRepositoryMockRecorder) GetByTagID(ctx, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTagID", reflect.TypeOf((*MockRepository)(nil).GetByTagID), ctx, tagID)
}

// SetTagsForCard mocks base method.
func (m *MockRepository) SetTagsForCard(ctx context.Context, cardID uuid.UUID, tagIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTagsForCard", ctx, cardID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTagsForCard indicates an expected call of SetTagsForCard.
func (mr *MockRepositoryMockRecorder) SetTagsForCard(ctx, cardID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTagsForCard", reflect.TypeOf((*MockRepository)(nil).SetTagsForCard), ctx, cardID, tagIDs)
}
