// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/card/card_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/card/card_repository.go -destination=internal/db/repositories/card/mocks/card_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	card "github.com/thatcatdev/kaimu/backend/internal/db/repositories/card"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *card.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// GetByAssigneeID mocks base method.
func (m *MockRepository) GetByAssigneeID(ctx context.Context, assigneeID uuid.UUID) ([]*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAssigneeID", ctx, assigneeID)
	ret0, _ := ret[0].([]*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAssigneeID indicates an expected call of GetByAssigneeID.
func (mr *MockRepositoryMockRecorder) GetByAssigneeID(ctx, assigneeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAssigneeID", reflect.TypeOf((*MockRepository)(nil).GetByAssigneeID), ctx, assigneeID)
}

// GetByBoardID mocks base method.
func (m *MockRepository) GetByBoardID(ctx context.Context, boardID uuid.UUID) ([]*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBoardID", ctx, boardID)
	ret0, _ := ret[0].([]*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBoardID indicates an expected call of GetByBoardID.
func (mr *MockRepositoryMockRecorder) GetByBoardID(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBoardID", reflect.TypeOf((*MockRepository)(nil).GetByBoardID), ctx, boardID)
}

// GetByColumnID mocks base method.
func (m *MockRepository) GetByColumnID(ctx context.Context, columnID uuid.UUID) ([]*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByColumnID", ctx, columnID)
	ret0, _ := ret[0].([]*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByColumnID indicates an expected call of GetByColumnID.
func (mr *MockRepositoryMockRecorder) GetByColumnID(ctx, columnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByColumnID", reflect.TypeOf((*MockRepository)(nil).GetByColumnID), ctx, columnID)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetMaxPosition mocks base method.
func (m *MockRepository) GetMaxPosition(ctx context.Context, columnID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxPosition", ctx, columnID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxPosition indicates an expected call of GetMaxPosition.
func (mr *MockRepositoryMockRecorder) GetMaxPosition(ctx, columnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxPosition", reflect.TypeOf((*MockRepository)(nil).GetMaxPosition), ctx, columnID)
}

// GetPositionBetween mocks base method.
func (m *MockRepository) GetPositionBetween(ctx context.Context, columnID uuid.UUID, afterCardID *uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPositionBetween", ctx, columnID, afterCardID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPositionBetween indicates an expected call of GetPositionBetween.
func (mr *MockRepositoryMockRecorder) GetPositionBetween(ctx, columnID, afterCardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPositionBetween", reflect.TypeOf((*MockRepository)(nil).GetPositionBetween), ctx, columnID, afterCardID)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *card.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1)
}
