package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"

	"github.com/thatcatdev/kaimu/backend/graph/model"
	"github.com/thatcatdev/kaimu/backend/internal/resolvers"
)

// OrganizationActivity is the resolver for the organizationActivity field.
func (r *queryResolver) OrganizationActivity(ctx context.Context, organizationID string, first *int, after *string, filters *model.AuditFilters) (*model.AuditEventConnection, error) {
	return resolvers.OrganizationActivity(ctx, r.RBACService, r.AuditService, r.getAuditServices(), organizationID, first, after, filters)
}

// ProjectActivity is the resolver for the projectActivity field.
func (r *queryResolver) ProjectActivity(ctx context.Context, projectID string, first *int, after *string) (*model.AuditEventConnection, error) {
	return resolvers.ProjectActivity(ctx, r.RBACService, r.AuditService, r.getAuditServices(), projectID, first, after)
}

// BoardActivity is the resolver for the boardActivity field.
func (r *queryResolver) BoardActivity(ctx context.Context, boardID string, first *int, after *string) (*model.AuditEventConnection, error) {
	return resolvers.BoardActivity(ctx, r.RBACService, r.AuditService, r.getAuditServices(), boardID, first, after)
}

// EntityHistory is the resolver for the entityHistory field.
func (r *queryResolver) EntityHistory(ctx context.Context, entityType model.AuditEntityType, entityID string, first *int, after *string) (*model.AuditEventConnection, error) {
	return resolvers.EntityHistory(ctx, r.RBACService, r.AuditService, r.getAuditServices(), entityType, entityID, first, after)
}

// UserActivity is the resolver for the userActivity field.
func (r *queryResolver) UserActivity(ctx context.Context, userID string, first *int, after *string) (*model.AuditEventConnection, error) {
	return resolvers.UserActivity(ctx, r.RBACService, r.AuditService, r.getAuditServices(), userID, first, after)
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) getAuditServices() *resolvers.AuditServices {
	return &resolvers.AuditServices{
		UserSvc:    r.UserService,
		OrgSvc:     r.OrganizationService,
		ProjectSvc: r.ProjectService,
		BoardSvc:   r.BoardService,
	}
}
