package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/thatcatdev/kaimu/backend/graph/generated"
	"github.com/thatcatdev/kaimu/backend/graph/model"
	"github.com/thatcatdev/kaimu/backend/http/middleware"
	"github.com/thatcatdev/kaimu/backend/internal/resolvers"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	isSecure := r.Config.AppConfig.Env != "development"
	payload, err := resolvers.Register(ctx, r.AuthService, input, isSecure)
	if err != nil {
		return nil, err
	}

	// Send verification email
	if r.EmailVerificationService != nil {
		userID, err := uuid.Parse(payload.User.ID)
		if err == nil {
			name := input.Username
			go r.EmailVerificationService.SendVerificationEmail(context.Background(), userID, input.Email, name)
		}
	}

	return payload, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	isSecure := r.Config.AppConfig.Env != "development"
	return resolvers.Login(ctx, r.AuthService, input, isSecure)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	return resolvers.Logout(ctx)
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (*model.AuthPayload, error) {
	if r.EmailVerificationService == nil {
		return nil, errors.New("email verification is not configured")
	}

	u, err := r.EmailVerificationService.VerifyEmail(ctx, token)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		User: resolvers.UserToModel(u),
	}, nil
}

// ResendVerificationEmail is the resolver for the resendVerificationEmail field.
func (r *mutationResolver) ResendVerificationEmail(ctx context.Context) (bool, error) {
	if r.EmailVerificationService == nil {
		return false, errors.New("email verification is not configured")
	}

	userID := middleware.GetUserIDFromContext(ctx)
	if userID == nil {
		return false, errors.New("not authenticated")
	}

	err := r.EmailVerificationService.ResendVerificationEmail(ctx, *userID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input model.UpdateMeInput) (*model.User, error) {
	return resolvers.UpdateMe(ctx, r.UserService, input)
}

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input model.CreateOrganizationInput) (*model.Organization, error) {
	return resolvers.CreateOrganization(ctx, r.OrganizationService, input)
}

// UpdateOrganization is the resolver for the updateOrganization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, input model.UpdateOrganizationInput) (*model.Organization, error) {
	return resolvers.UpdateOrganization(ctx, r.OrganizationService, input)
}

// DeleteOrganization is the resolver for the deleteOrganization field.
func (r *mutationResolver) DeleteOrganization(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteOrganization(ctx, r.OrganizationService, id)
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	project, err := resolvers.CreateProject(ctx, r.RBACService, r.OrganizationService, r.ProjectService, r.BoardService, input)
	if err != nil {
		return nil, err
	}

	// Index for search
	if r.SearchIndexer != nil {
		projectID, _ := uuid.Parse(project.ID)
		r.SearchIndexer.IndexProjectAsync(ctx, projectID)
	}

	return project, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, input model.UpdateProjectInput) (*model.Project, error) {
	project, err := resolvers.UpdateProject(ctx, r.RBACService, r.ProjectService, input)
	if err != nil {
		return nil, err
	}

	// Index for search
	if r.SearchIndexer != nil {
		projectID, _ := uuid.Parse(project.ID)
		r.SearchIndexer.IndexProjectAsync(ctx, projectID)
	}

	return project, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	result, err := resolvers.DeleteProject(ctx, r.RBACService, r.ProjectService, id)
	if err != nil {
		return false, err
	}

	// Remove from search index
	if r.SearchIndexer != nil {
		r.SearchIndexer.DeleteProjectAsync(ctx, id)
	}

	return result, nil
}

// CreateBoard is the resolver for the createBoard field.
func (r *mutationResolver) CreateBoard(ctx context.Context, input model.CreateBoardInput) (*model.Board, error) {
	board, err := resolvers.CreateBoard(ctx, r.RBACService, r.BoardService, r.ProjectService, input)
	if err != nil {
		return nil, err
	}

	// Index for search
	if r.SearchIndexer != nil {
		boardID, _ := uuid.Parse(board.ID)
		r.SearchIndexer.IndexBoardAsync(ctx, boardID)
	}

	return board, nil
}

// UpdateBoard is the resolver for the updateBoard field.
func (r *mutationResolver) UpdateBoard(ctx context.Context, input model.UpdateBoardInput) (*model.Board, error) {
	board, err := resolvers.UpdateBoard(ctx, r.RBACService, r.BoardService, input)
	if err != nil {
		return nil, err
	}

	// Index for search
	if r.SearchIndexer != nil {
		boardID, _ := uuid.Parse(board.ID)
		r.SearchIndexer.IndexBoardAsync(ctx, boardID)
	}

	return board, nil
}

// DeleteBoard is the resolver for the deleteBoard field.
func (r *mutationResolver) DeleteBoard(ctx context.Context, id string) (bool, error) {
	result, err := resolvers.DeleteBoard(ctx, r.RBACService, r.BoardService, id)
	if err != nil {
		return false, err
	}

	// Remove from search index
	if r.SearchIndexer != nil {
		r.SearchIndexer.DeleteBoardAsync(ctx, id)
	}

	return result, nil
}

// CreateColumn is the resolver for the createColumn field.
func (r *mutationResolver) CreateColumn(ctx context.Context, input model.CreateColumnInput) (*model.BoardColumn, error) {
	return resolvers.CreateColumn(ctx, r.RBACService, r.BoardService, input)
}

// UpdateColumn is the resolver for the updateColumn field.
func (r *mutationResolver) UpdateColumn(ctx context.Context, input model.UpdateColumnInput) (*model.BoardColumn, error) {
	return resolvers.UpdateColumn(ctx, r.RBACService, r.BoardService, input)
}

// ReorderColumns is the resolver for the reorderColumns field.
func (r *mutationResolver) ReorderColumns(ctx context.Context, input model.ReorderColumnsInput) ([]*model.BoardColumn, error) {
	return resolvers.ReorderColumns(ctx, r.RBACService, r.BoardService, input)
}

// ToggleColumnVisibility is the resolver for the toggleColumnVisibility field.
func (r *mutationResolver) ToggleColumnVisibility(ctx context.Context, id string) (*model.BoardColumn, error) {
	return resolvers.ToggleColumnVisibility(ctx, r.RBACService, r.BoardService, id)
}

// DeleteColumn is the resolver for the deleteColumn field.
func (r *mutationResolver) DeleteColumn(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteColumn(ctx, r.RBACService, r.BoardService, id)
}

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, input model.CreateCardInput) (*model.Card, error) {
	card, err := resolvers.CreateCard(ctx, r.RBACService, r.CardService, r.BoardService, input)
	if err != nil {
		return nil, err
	}

	// Index for search
	if r.SearchIndexer != nil {
		cardID, _ := uuid.Parse(card.ID)
		r.SearchIndexer.IndexCardAsync(ctx, cardID)
	}

	return card, nil
}

// UpdateCard is the resolver for the updateCard field.
func (r *mutationResolver) UpdateCard(ctx context.Context, input model.UpdateCardInput) (*model.Card, error) {
	card, err := resolvers.UpdateCard(ctx, r.RBACService, r.CardService, r.BoardService, input)
	if err != nil {
		return nil, err
	}

	// Index for search
	if r.SearchIndexer != nil {
		cardID, _ := uuid.Parse(card.ID)
		r.SearchIndexer.IndexCardAsync(ctx, cardID)
	}

	return card, nil
}

// MoveCard is the resolver for the moveCard field.
func (r *mutationResolver) MoveCard(ctx context.Context, input model.MoveCardInput) (*model.Card, error) {
	card, err := resolvers.MoveCard(ctx, r.RBACService, r.CardService, r.BoardService, input)
	if err != nil {
		return nil, err
	}

	// Index for search
	if r.SearchIndexer != nil {
		cardID, _ := uuid.Parse(card.ID)
		r.SearchIndexer.IndexCardAsync(ctx, cardID)
	}

	return card, nil
}

// DeleteCard is the resolver for the deleteCard field.
func (r *mutationResolver) DeleteCard(ctx context.Context, id string) (bool, error) {
	result, err := resolvers.DeleteCard(ctx, r.RBACService, r.CardService, r.BoardService, id)
	if err != nil {
		return false, err
	}

	// Remove from search index
	if r.SearchIndexer != nil {
		r.SearchIndexer.DeleteCardAsync(ctx, id)
	}

	return result, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.Tag, error) {
	return resolvers.CreateTag(ctx, r.OrganizationService, r.TagService, r.ProjectService, input)
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, input model.UpdateTagInput) (*model.Tag, error) {
	return resolvers.UpdateTag(ctx, r.OrganizationService, r.TagService, input)
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteTag(ctx, r.OrganizationService, r.TagService, id)
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input model.CreateRoleInput) (*model.Role, error) {
	return resolvers.CreateRole(ctx, r.RBACService, input)
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, input model.UpdateRoleInput) (*model.Role, error) {
	return resolvers.UpdateRole(ctx, r.RBACService, input)
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteRole(ctx, r.RBACService, id)
}

// InviteMember is the resolver for the inviteMember field.
func (r *mutationResolver) InviteMember(ctx context.Context, input model.InviteMemberInput) (*model.Invitation, error) {
	return resolvers.InviteMember(ctx, r.InvitationService, r.RBACService, input)
}

// CancelInvitation is the resolver for the cancelInvitation field.
func (r *mutationResolver) CancelInvitation(ctx context.Context, id string) (bool, error) {
	return resolvers.CancelInvitation(ctx, r.InvitationService, r.RBACService, id)
}

// ResendInvitation is the resolver for the resendInvitation field.
func (r *mutationResolver) ResendInvitation(ctx context.Context, id string) (*model.Invitation, error) {
	return resolvers.ResendInvitation(ctx, r.InvitationService, r.RBACService, id)
}

// AcceptInvitation is the resolver for the acceptInvitation field.
func (r *mutationResolver) AcceptInvitation(ctx context.Context, token string) (*model.Organization, error) {
	return resolvers.AcceptInvitation(ctx, r.InvitationService, token)
}

// ChangeMemberRole is the resolver for the changeMemberRole field.
func (r *mutationResolver) ChangeMemberRole(ctx context.Context, organizationID string, input model.ChangeMemberRoleInput) (*model.OrganizationMember, error) {
	return resolvers.ChangeMemberRole(ctx, r.RBACService, organizationID, input)
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, organizationID string, userID string) (bool, error) {
	return resolvers.RemoveMember(ctx, r.RBACService, organizationID, userID)
}

// AssignProjectRole is the resolver for the assignProjectRole field.
func (r *mutationResolver) AssignProjectRole(ctx context.Context, input model.AssignProjectRoleInput) (*model.ProjectMember, error) {
	return resolvers.AssignProjectRole(ctx, r.RBACService, input)
}

// RemoveProjectMember is the resolver for the removeProjectMember field.
func (r *mutationResolver) RemoveProjectMember(ctx context.Context, projectID string, userID string) (bool, error) {
	return resolvers.RemoveProjectMember(ctx, r.RBACService, projectID, userID)
}

// CreateSprint is the resolver for the createSprint field.
func (r *mutationResolver) CreateSprint(ctx context.Context, input model.CreateSprintInput) (*model.Sprint, error) {
	return resolvers.CreateSprint(ctx, r.RBACService, r.SprintService, input)
}

// UpdateSprint is the resolver for the updateSprint field.
func (r *mutationResolver) UpdateSprint(ctx context.Context, id string, input model.UpdateSprintInput) (*model.Sprint, error) {
	return resolvers.UpdateSprint(ctx, r.RBACService, r.SprintService, id, input)
}

// DeleteSprint is the resolver for the deleteSprint field.
func (r *mutationResolver) DeleteSprint(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteSprint(ctx, r.RBACService, r.SprintService, id)
}

// StartSprint is the resolver for the startSprint field.
func (r *mutationResolver) StartSprint(ctx context.Context, id string) (*model.Sprint, error) {
	return resolvers.StartSprint(ctx, r.RBACService, r.SprintService, id)
}

// CompleteSprint is the resolver for the completeSprint field.
func (r *mutationResolver) CompleteSprint(ctx context.Context, id string, moveIncompleteToBacklog *bool) (*model.Sprint, error) {
	moveToBacklog := true
	if moveIncompleteToBacklog != nil {
		moveToBacklog = *moveIncompleteToBacklog
	}
	return resolvers.CompleteSprint(ctx, r.RBACService, r.SprintService, id, moveToBacklog)
}

// AddCardToSprint is the resolver for the addCardToSprint field.
func (r *mutationResolver) AddCardToSprint(ctx context.Context, input model.MoveCardToSprintInput) (*model.Card, error) {
	return resolvers.AddCardToSprint(ctx, r.RBACService, r.SprintService, input)
}

// RemoveCardFromSprint is the resolver for the removeCardFromSprint field.
func (r *mutationResolver) RemoveCardFromSprint(ctx context.Context, input model.MoveCardToSprintInput) (*model.Card, error) {
	return resolvers.RemoveCardFromSprint(ctx, r.RBACService, r.SprintService, input)
}

// SetCardSprints is the resolver for the setCardSprints field.
func (r *mutationResolver) SetCardSprints(ctx context.Context, cardID string, sprintIds []string) (*model.Card, error) {
	return resolvers.SetCardSprints(ctx, r.RBACService, r.SprintService, cardID, sprintIds)
}

// MoveCardToBacklog is the resolver for the moveCardToBacklog field.
func (r *mutationResolver) MoveCardToBacklog(ctx context.Context, cardID string) (*model.Card, error) {
	return resolvers.MoveCardToBacklog(ctx, r.RBACService, r.SprintService, r.BoardService, cardID)
}

// HelloWorld is the resolver for the helloWorld field.
func (r *queryResolver) HelloWorld(ctx context.Context) (string, error) {
	return resolvers.Hello(), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return resolvers.Me(ctx, r.AuthService)
}

// OidcProviders is the resolver for the oidcProviders field.
func (r *queryResolver) OidcProviders(ctx context.Context) ([]*model.OIDCProvider, error) {
	providers, err := r.OIDCService.GetProviders(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.OIDCProvider, len(providers))
	for i, p := range providers {
		result[i] = &model.OIDCProvider{
			Slug: p.Slug,
			Name: p.Name,
		}
	}
	return result, nil
}

// Organizations is the resolver for the organizations field.
func (r *queryResolver) Organizations(ctx context.Context) ([]*model.Organization, error) {
	return resolvers.Organizations(ctx, r.OrganizationService, r.ProjectService, r.BoardService)
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, id string) (*model.Organization, error) {
	return resolvers.Organization(ctx, r.OrganizationService, r.ProjectService, id)
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	return resolvers.Project(ctx, r.RBACService, r.ProjectService, id)
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id string) (*model.Board, error) {
	return resolvers.Board(ctx, r.RBACService, r.BoardService, r.ProjectService, id)
}

// Boards is the resolver for the boards field.
func (r *queryResolver) Boards(ctx context.Context, projectID string) ([]*model.Board, error) {
	return resolvers.Boards(ctx, r.RBACService, r.BoardService, r.ProjectService, projectID)
}

// Card is the resolver for the card field.
func (r *queryResolver) Card(ctx context.Context, id string) (*model.Card, error) {
	return resolvers.Card(ctx, r.RBACService, r.CardService, r.BoardService, id)
}

// MyCards is the resolver for the myCards field.
func (r *queryResolver) MyCards(ctx context.Context) ([]*model.Card, error) {
	return resolvers.MyCards(ctx, r.CardService)
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, projectID string) ([]*model.Tag, error) {
	return resolvers.Tags(ctx, r.OrganizationService, r.TagService, r.ProjectService, projectID)
}

// Permissions is the resolver for the permissions field.
func (r *queryResolver) Permissions(ctx context.Context) ([]*model.Permission, error) {
	return resolvers.Permissions(ctx, r.RBACService)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context, organizationID string) ([]*model.Role, error) {
	return resolvers.Roles(ctx, r.RBACService, organizationID)
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*model.Role, error) {
	return resolvers.Role(ctx, r.RBACService, id)
}

// OrganizationMembers is the resolver for the organizationMembers field.
func (r *queryResolver) OrganizationMembers(ctx context.Context, organizationID string) ([]*model.OrganizationMember, error) {
	return resolvers.GetOrganizationMembersRBAC(ctx, r.RBACService, organizationID)
}

// ProjectMembers is the resolver for the projectMembers field.
func (r *queryResolver) ProjectMembers(ctx context.Context, projectID string) ([]*model.ProjectMember, error) {
	return resolvers.ProjectMembers(ctx, r.RBACService, projectID)
}

// Invitations is the resolver for the invitations field.
func (r *queryResolver) Invitations(ctx context.Context, organizationID string) ([]*model.Invitation, error) {
	return resolvers.Invitations(ctx, r.InvitationService, r.RBACService, organizationID)
}

// HasPermission is the resolver for the hasPermission field.
func (r *queryResolver) HasPermission(ctx context.Context, permission string, resourceType string, resourceID string) (bool, error) {
	return resolvers.HasPermission(ctx, r.RBACService, permission, resourceType, resourceID)
}

// MyPermissions is the resolver for the myPermissions field.
func (r *queryResolver) MyPermissions(ctx context.Context, resourceType string, resourceID string) ([]string, error) {
	return resolvers.MyPermissions(ctx, r.RBACService, resourceType, resourceID)
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, scope *model.SearchScope, limit *int) (*model.SearchResults, error) {
	if r.SearchService == nil {
		return nil, errors.New("search service is not configured")
	}
	return resolvers.Search(ctx, r.SearchService, query, scope, limit)
}

// Sprint is the resolver for the sprint field.
func (r *queryResolver) Sprint(ctx context.Context, id string) (*model.Sprint, error) {
	return resolvers.Sprint(ctx, r.RBACService, r.SprintService, id)
}

// Sprints is the resolver for the sprints field.
func (r *queryResolver) Sprints(ctx context.Context, boardID string) ([]*model.Sprint, error) {
	return resolvers.Sprints(ctx, r.RBACService, r.SprintService, boardID)
}

// ActiveSprint is the resolver for the activeSprint field.
func (r *queryResolver) ActiveSprint(ctx context.Context, boardID string) (*model.Sprint, error) {
	return resolvers.ActiveSprint(ctx, r.RBACService, r.SprintService, boardID)
}

// FutureSprints is the resolver for the futureSprints field.
func (r *queryResolver) FutureSprints(ctx context.Context, boardID string) ([]*model.Sprint, error) {
	return resolvers.FutureSprints(ctx, r.RBACService, r.SprintService, boardID)
}

// ClosedSprints is the resolver for the closedSprints field.
func (r *queryResolver) ClosedSprints(ctx context.Context, boardID string, first *int, after *string) (*model.SprintConnection, error) {
	return resolvers.ClosedSprints(ctx, r.RBACService, r.SprintService, boardID, first, after)
}

// SprintCards is the resolver for the sprintCards field.
func (r *queryResolver) SprintCards(ctx context.Context, sprintID string) ([]*model.Card, error) {
	return resolvers.SprintCards(ctx, r.RBACService, r.SprintService, sprintID)
}

// BacklogCards is the resolver for the backlogCards field.
func (r *queryResolver) BacklogCards(ctx context.Context, boardID string) ([]*model.Card, error) {
	return resolvers.BacklogCards(ctx, r.RBACService, r.SprintService, r.BoardService, boardID)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
