package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"

	"github.com/thatcatdev/pulse-backend/graph/generated"
	"github.com/thatcatdev/pulse-backend/graph/model"
	"github.com/thatcatdev/pulse-backend/internal/resolvers"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	isSecure := r.Config.AppConfig.Env != "development"
	return resolvers.Register(ctx, r.AuthService, input, isSecure)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	isSecure := r.Config.AppConfig.Env != "development"
	return resolvers.Login(ctx, r.AuthService, input, isSecure)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	return resolvers.Logout(ctx)
}

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input model.CreateOrganizationInput) (*model.Organization, error) {
	return resolvers.CreateOrganization(ctx, r.OrganizationService, input)
}

// DeleteOrganization is the resolver for the deleteOrganization field.
func (r *mutationResolver) DeleteOrganization(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteOrganization(ctx, r.OrganizationService, id)
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	return resolvers.CreateProject(ctx, r.OrganizationService, r.ProjectService, r.BoardService, input)
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteProject(ctx, r.OrganizationService, r.ProjectService, id)
}

// CreateBoard is the resolver for the createBoard field.
func (r *mutationResolver) CreateBoard(ctx context.Context, input model.CreateBoardInput) (*model.Board, error) {
	return resolvers.CreateBoard(ctx, r.OrganizationService, r.BoardService, r.ProjectService, input)
}

// UpdateBoard is the resolver for the updateBoard field.
func (r *mutationResolver) UpdateBoard(ctx context.Context, input model.UpdateBoardInput) (*model.Board, error) {
	return resolvers.UpdateBoard(ctx, r.OrganizationService, r.BoardService, input)
}

// DeleteBoard is the resolver for the deleteBoard field.
func (r *mutationResolver) DeleteBoard(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteBoard(ctx, r.OrganizationService, r.BoardService, id)
}

// CreateColumn is the resolver for the createColumn field.
func (r *mutationResolver) CreateColumn(ctx context.Context, input model.CreateColumnInput) (*model.BoardColumn, error) {
	return resolvers.CreateColumn(ctx, r.OrganizationService, r.BoardService, input)
}

// UpdateColumn is the resolver for the updateColumn field.
func (r *mutationResolver) UpdateColumn(ctx context.Context, input model.UpdateColumnInput) (*model.BoardColumn, error) {
	return resolvers.UpdateColumn(ctx, r.OrganizationService, r.BoardService, input)
}

// ReorderColumns is the resolver for the reorderColumns field.
func (r *mutationResolver) ReorderColumns(ctx context.Context, input model.ReorderColumnsInput) ([]*model.BoardColumn, error) {
	return resolvers.ReorderColumns(ctx, r.OrganizationService, r.BoardService, input)
}

// ToggleColumnVisibility is the resolver for the toggleColumnVisibility field.
func (r *mutationResolver) ToggleColumnVisibility(ctx context.Context, id string) (*model.BoardColumn, error) {
	return resolvers.ToggleColumnVisibility(ctx, r.OrganizationService, r.BoardService, id)
}

// DeleteColumn is the resolver for the deleteColumn field.
func (r *mutationResolver) DeleteColumn(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteColumn(ctx, r.OrganizationService, r.BoardService, id)
}

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, input model.CreateCardInput) (*model.Card, error) {
	return resolvers.CreateCard(ctx, r.OrganizationService, r.CardService, r.BoardService, input)
}

// UpdateCard is the resolver for the updateCard field.
func (r *mutationResolver) UpdateCard(ctx context.Context, input model.UpdateCardInput) (*model.Card, error) {
	return resolvers.UpdateCard(ctx, r.OrganizationService, r.CardService, r.BoardService, input)
}

// MoveCard is the resolver for the moveCard field.
func (r *mutationResolver) MoveCard(ctx context.Context, input model.MoveCardInput) (*model.Card, error) {
	return resolvers.MoveCard(ctx, r.OrganizationService, r.CardService, r.BoardService, input)
}

// DeleteCard is the resolver for the deleteCard field.
func (r *mutationResolver) DeleteCard(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteCard(ctx, r.OrganizationService, r.CardService, r.BoardService, id)
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.Tag, error) {
	return resolvers.CreateTag(ctx, r.OrganizationService, r.TagService, r.ProjectService, input)
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, input model.UpdateTagInput) (*model.Tag, error) {
	return resolvers.UpdateTag(ctx, r.OrganizationService, r.TagService, input)
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id string) (bool, error) {
	return resolvers.DeleteTag(ctx, r.OrganizationService, r.TagService, id)
}

// HelloWorld is the resolver for the helloWorld field.
func (r *queryResolver) HelloWorld(ctx context.Context) (string, error) {
	return resolvers.Hello(), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return resolvers.Me(ctx, r.AuthService)
}

// Organizations is the resolver for the organizations field.
func (r *queryResolver) Organizations(ctx context.Context) ([]*model.Organization, error) {
	return resolvers.Organizations(ctx, r.OrganizationService)
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, id string) (*model.Organization, error) {
	return resolvers.Organization(ctx, r.OrganizationService, r.ProjectService, id)
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	return resolvers.Project(ctx, r.OrganizationService, r.ProjectService, id)
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id string) (*model.Board, error) {
	return resolvers.Board(ctx, r.OrganizationService, r.BoardService, r.ProjectService, id)
}

// Boards is the resolver for the boards field.
func (r *queryResolver) Boards(ctx context.Context, projectID string) ([]*model.Board, error) {
	return resolvers.Boards(ctx, r.OrganizationService, r.BoardService, r.ProjectService, projectID)
}

// Card is the resolver for the card field.
func (r *queryResolver) Card(ctx context.Context, id string) (*model.Card, error) {
	return resolvers.Card(ctx, r.OrganizationService, r.CardService, r.BoardService, id)
}

// MyCards is the resolver for the myCards field.
func (r *queryResolver) MyCards(ctx context.Context) ([]*model.Card, error) {
	return resolvers.MyCards(ctx, r.CardService)
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, projectID string) ([]*model.Tag, error) {
	return resolvers.Tags(ctx, r.OrganizationService, r.TagService, r.ProjectService, projectID)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
