package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"

	"github.com/thatcatdev/kaimu/backend/graph/generated"
	"github.com/thatcatdev/kaimu/backend/graph/model"
	"github.com/thatcatdev/kaimu/backend/internal/resolvers"
)

// Project is the resolver for the project field.
func (r *boardResolver) Project(ctx context.Context, obj *model.Board) (*model.Project, error) {
	return resolvers.BoardProject(ctx, r.BoardService, r.OrganizationService, obj)
}

// Columns is the resolver for the columns field.
func (r *boardResolver) Columns(ctx context.Context, obj *model.Board) ([]*model.BoardColumn, error) {
	return resolvers.BoardColumns(ctx, r.BoardService, obj)
}

// Sprints is the resolver for the sprints field.
func (r *boardResolver) Sprints(ctx context.Context, obj *model.Board) ([]*model.Sprint, error) {
	return resolvers.BoardSprints(ctx, r.SprintService, obj)
}

// ActiveSprint is the resolver for the activeSprint field.
func (r *boardResolver) ActiveSprint(ctx context.Context, obj *model.Board) (*model.Sprint, error) {
	return resolvers.BoardActiveSprint(ctx, r.SprintService, obj)
}

// Board is the resolver for the board field.
func (r *boardColumnResolver) Board(ctx context.Context, obj *model.BoardColumn) (*model.Board, error) {
	return resolvers.ColumnBoard(ctx, r.BoardService, obj)
}

// Cards is the resolver for the cards field.
func (r *boardColumnResolver) Cards(ctx context.Context, obj *model.BoardColumn) ([]*model.Card, error) {
	return resolvers.ColumnCards(ctx, r.CardService, obj)
}

// Column is the resolver for the column field.
func (r *cardResolver) Column(ctx context.Context, obj *model.Card) (*model.BoardColumn, error) {
	return resolvers.CardColumn(ctx, r.CardService, obj)
}

// Board is the resolver for the board field.
func (r *cardResolver) Board(ctx context.Context, obj *model.Card) (*model.Board, error) {
	return resolvers.CardBoard(ctx, r.CardService, obj)
}

// Sprints is the resolver for the sprints field.
func (r *cardResolver) Sprints(ctx context.Context, obj *model.Card) ([]*model.Sprint, error) {
	return resolvers.CardSprints(ctx, r.SprintService, obj)
}

// Assignee is the resolver for the assignee field.
func (r *cardResolver) Assignee(ctx context.Context, obj *model.Card) (*model.User, error) {
	return resolvers.CardAssignee(ctx, r.CardService, r.UserService, obj)
}

// Tags is the resolver for the tags field.
func (r *cardResolver) Tags(ctx context.Context, obj *model.Card) ([]*model.Tag, error) {
	return resolvers.CardTags(ctx, r.CardService, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *cardResolver) CreatedBy(ctx context.Context, obj *model.Card) (*model.User, error) {
	return resolvers.CardCreatedBy(ctx, r.CardService, r.UserService, obj)
}

// Role is the resolver for the role field.
func (r *invitationResolver) Role(ctx context.Context, obj *model.Invitation) (*model.Role, error) {
	return resolvers.InvitationRole(ctx, r.InvitationService, obj)
}

// Organization is the resolver for the organization field.
func (r *invitationResolver) Organization(ctx context.Context, obj *model.Invitation) (*model.Organization, error) {
	return resolvers.InvitationOrganization(ctx, r.InvitationService, obj)
}

// InvitedBy is the resolver for the invitedBy field.
func (r *invitationResolver) InvitedBy(ctx context.Context, obj *model.Invitation) (*model.User, error) {
	return resolvers.InvitationInvitedBy(ctx, r.InvitationService, obj)
}

// User is the resolver for the user field.
func (r *organizationMemberResolver) User(ctx context.Context, obj *model.OrganizationMember) (*model.User, error) {
	return resolvers.OrgMemberUser(ctx, r.RBACService, obj)
}

// Role is the resolver for the role field.
func (r *organizationMemberResolver) Role(ctx context.Context, obj *model.OrganizationMember) (*model.Role, error) {
	return resolvers.OrgMemberRole(ctx, r.RBACService, obj)
}

// Boards is the resolver for the boards field.
func (r *projectResolver) Boards(ctx context.Context, obj *model.Project) ([]*model.Board, error) {
	return resolvers.ProjectBoards(ctx, r.BoardService, obj)
}

// DefaultBoard is the resolver for the defaultBoard field.
func (r *projectResolver) DefaultBoard(ctx context.Context, obj *model.Project) (*model.Board, error) {
	return resolvers.ProjectDefaultBoard(ctx, r.BoardService, obj)
}

// Tags is the resolver for the tags field.
func (r *projectResolver) Tags(ctx context.Context, obj *model.Project) ([]*model.Tag, error) {
	return resolvers.ProjectTags(ctx, r.TagService, obj)
}

// User is the resolver for the user field.
func (r *projectMemberResolver) User(ctx context.Context, obj *model.ProjectMember) (*model.User, error) {
	return resolvers.ProjectMemberUser(ctx, r.RBACService, obj)
}

// Role is the resolver for the role field.
func (r *projectMemberResolver) Role(ctx context.Context, obj *model.ProjectMember) (*model.Role, error) {
	return resolvers.ProjectMemberRole(ctx, r.RBACService, obj)
}

// Project is the resolver for the project field.
func (r *projectMemberResolver) Project(ctx context.Context, obj *model.ProjectMember) (*model.Project, error) {
	return resolvers.ProjectMemberProject(ctx, r.RBACService, obj)
}

// Permissions is the resolver for the permissions field.
func (r *roleResolver) Permissions(ctx context.Context, obj *model.Role) ([]*model.Permission, error) {
	return resolvers.RolePermissions(ctx, r.RBACService, obj)
}

// Board is the resolver for the board field.
func (r *sprintResolver) Board(ctx context.Context, obj *model.Sprint) (*model.Board, error) {
	return resolvers.SprintBoard(ctx, r.SprintService, obj)
}

// Cards is the resolver for the cards field.
func (r *sprintResolver) Cards(ctx context.Context, obj *model.Sprint) ([]*model.Card, error) {
	return resolvers.SprintCardsResolver(ctx, r.SprintService, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *sprintResolver) CreatedBy(ctx context.Context, obj *model.Sprint) (*model.User, error) {
	return resolvers.SprintCreatedBy(ctx, r.UserService, r.SprintService, obj)
}

// Project is the resolver for the project field.
func (r *tagResolver) Project(ctx context.Context, obj *model.Tag) (*model.Project, error) {
	return resolvers.TagProject(ctx, r.TagService, r.OrganizationService, obj)
}

// Board returns generated.BoardResolver implementation.
func (r *Resolver) Board() generated.BoardResolver { return &boardResolver{r} }

// BoardColumn returns generated.BoardColumnResolver implementation.
func (r *Resolver) BoardColumn() generated.BoardColumnResolver { return &boardColumnResolver{r} }

// Card returns generated.CardResolver implementation.
func (r *Resolver) Card() generated.CardResolver { return &cardResolver{r} }

// Invitation returns generated.InvitationResolver implementation.
func (r *Resolver) Invitation() generated.InvitationResolver { return &invitationResolver{r} }

// OrganizationMember returns generated.OrganizationMemberResolver implementation.
func (r *Resolver) OrganizationMember() generated.OrganizationMemberResolver {
	return &organizationMemberResolver{r}
}

// Project returns generated.ProjectResolver implementation.
func (r *Resolver) Project() generated.ProjectResolver { return &projectResolver{r} }

// ProjectMember returns generated.ProjectMemberResolver implementation.
func (r *Resolver) ProjectMember() generated.ProjectMemberResolver { return &projectMemberResolver{r} }

// Role returns generated.RoleResolver implementation.
func (r *Resolver) Role() generated.RoleResolver { return &roleResolver{r} }

// Sprint returns generated.SprintResolver implementation.
func (r *Resolver) Sprint() generated.SprintResolver { return &sprintResolver{r} }

// Tag returns generated.TagResolver implementation.
func (r *Resolver) Tag() generated.TagResolver { return &tagResolver{r} }

type boardResolver struct{ *Resolver }
type boardColumnResolver struct{ *Resolver }
type cardResolver struct{ *Resolver }
type invitationResolver struct{ *Resolver }
type organizationMemberResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type projectMemberResolver struct{ *Resolver }
type roleResolver struct{ *Resolver }
type sprintResolver struct{ *Resolver }
type tagResolver struct{ *Resolver }
