package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"

	"github.com/thatcatdev/pulse-backend/graph/generated"
	"github.com/thatcatdev/pulse-backend/graph/model"
	"github.com/thatcatdev/pulse-backend/internal/resolvers"
)

// Project is the resolver for the project field.
func (r *boardResolver) Project(ctx context.Context, obj *model.Board) (*model.Project, error) {
	return resolvers.BoardProject(ctx, r.BoardService, r.OrganizationService, obj)
}

// Columns is the resolver for the columns field.
func (r *boardResolver) Columns(ctx context.Context, obj *model.Board) ([]*model.BoardColumn, error) {
	return resolvers.BoardColumns(ctx, r.BoardService, obj)
}

// Board is the resolver for the board field.
func (r *boardColumnResolver) Board(ctx context.Context, obj *model.BoardColumn) (*model.Board, error) {
	return resolvers.ColumnBoard(ctx, r.BoardService, obj)
}

// Cards is the resolver for the cards field.
func (r *boardColumnResolver) Cards(ctx context.Context, obj *model.BoardColumn) ([]*model.Card, error) {
	return resolvers.ColumnCards(ctx, r.CardService, obj)
}

// Column is the resolver for the column field.
func (r *cardResolver) Column(ctx context.Context, obj *model.Card) (*model.BoardColumn, error) {
	return resolvers.CardColumn(ctx, r.CardService, obj)
}

// Board is the resolver for the board field.
func (r *cardResolver) Board(ctx context.Context, obj *model.Card) (*model.Board, error) {
	return resolvers.CardBoard(ctx, r.CardService, obj)
}

// Assignee is the resolver for the assignee field.
func (r *cardResolver) Assignee(ctx context.Context, obj *model.Card) (*model.User, error) {
	return resolvers.CardAssignee(ctx, r.CardService, obj)
}

// Labels is the resolver for the labels field.
func (r *cardResolver) Labels(ctx context.Context, obj *model.Card) ([]*model.Label, error) {
	return resolvers.CardLabels(ctx, r.CardService, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *cardResolver) CreatedBy(ctx context.Context, obj *model.Card) (*model.User, error) {
	return resolvers.CardCreatedBy(ctx, r.CardService, obj)
}

// Project is the resolver for the project field.
func (r *labelResolver) Project(ctx context.Context, obj *model.Label) (*model.Project, error) {
	return resolvers.LabelProject(ctx, r.LabelService, r.OrganizationService, obj)
}

// Boards is the resolver for the boards field.
func (r *projectResolver) Boards(ctx context.Context, obj *model.Project) ([]*model.Board, error) {
	return resolvers.ProjectBoards(ctx, r.BoardService, obj)
}

// DefaultBoard is the resolver for the defaultBoard field.
func (r *projectResolver) DefaultBoard(ctx context.Context, obj *model.Project) (*model.Board, error) {
	return resolvers.ProjectDefaultBoard(ctx, r.BoardService, obj)
}

// Labels is the resolver for the labels field.
func (r *projectResolver) Labels(ctx context.Context, obj *model.Project) ([]*model.Label, error) {
	return resolvers.ProjectLabels(ctx, r.LabelService, obj)
}

// Board returns generated.BoardResolver implementation.
func (r *Resolver) Board() generated.BoardResolver { return &boardResolver{r} }

// BoardColumn returns generated.BoardColumnResolver implementation.
func (r *Resolver) BoardColumn() generated.BoardColumnResolver { return &boardColumnResolver{r} }

// Card returns generated.CardResolver implementation.
func (r *Resolver) Card() generated.CardResolver { return &cardResolver{r} }

// Label returns generated.LabelResolver implementation.
func (r *Resolver) Label() generated.LabelResolver { return &labelResolver{r} }

// Project returns generated.ProjectResolver implementation.
func (r *Resolver) Project() generated.ProjectResolver { return &projectResolver{r} }

type boardResolver struct{ *Resolver }
type boardColumnResolver struct{ *Resolver }
type cardResolver struct{ *Resolver }
type labelResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
