// Code generated by MockGen. DO NOT EDIT.
// Source: role_repository.go
//
// Generated by this command:
//
//	mockgen -source=role_repository.go -destination=mocks/role_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	role "github.com/thatcatdev/kaimu/backend/internal/db/repositories/role"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *role.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// GetAllForOrg mocks base method.
func (m *MockRepository) GetAllForOrg(ctx context.Context, orgID uuid.UUID) ([]*role.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForOrg", ctx, orgID)
	ret0, _ := ret[0].([]*role.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForOrg indicates an expected call of GetAllForOrg.
func (mr *MockRepositoryMockRecorder) GetAllForOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForOrg", reflect.TypeOf((*MockRepository)(nil).GetAllForOrg), ctx, orgID)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*role.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*role.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetByOrgID mocks base method.
func (m *MockRepository) GetByOrgID(ctx context.Context, orgID uuid.UUID) ([]*role.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgID", ctx, orgID)
	ret0, _ := ret[0].([]*role.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrgID indicates an expected call of GetByOrgID.
func (mr *MockRepositoryMockRecorder) GetByOrgID(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgID", reflect.TypeOf((*MockRepository)(nil).GetByOrgID), ctx, orgID)
}

// GetSystemRoles mocks base method.
func (m *MockRepository) GetSystemRoles(ctx context.Context) ([]*role.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemRoles", ctx)
	ret0, _ := ret[0].([]*role.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemRoles indicates an expected call of GetSystemRoles.
func (mr *MockRepositoryMockRecorder) GetSystemRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemRoles", reflect.TypeOf((*MockRepository)(nil).GetSystemRoles), ctx)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *role.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1)
}
