// Code generated by MockGen. DO NOT EDIT.
// Source: sprint_repository.go
//
// Generated by this command:
//
//	mockgen -source=sprint_repository.go -destination=mocks/sprint_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	sprint "github.com/thatcatdev/kaimu/backend/internal/db/repositories/sprint"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *sprint.Sprint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// GetActiveByBoardID mocks base method.
func (m *MockRepository) GetActiveByBoardID(ctx context.Context, boardID uuid.UUID) (*sprint.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByBoardID", ctx, boardID)
	ret0, _ := ret[0].(*sprint.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByBoardID indicates an expected call of GetActiveByBoardID.
func (mr *MockRepositoryMockRecorder) GetActiveByBoardID(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByBoardID", reflect.TypeOf((*MockRepository)(nil).GetActiveByBoardID), ctx, boardID)
}

// GetByBoardID mocks base method.
func (m *MockRepository) GetByBoardID(ctx context.Context, boardID uuid.UUID) ([]*sprint.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBoardID", ctx, boardID)
	ret0, _ := ret[0].([]*sprint.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBoardID indicates an expected call of GetByBoardID.
func (mr *MockRepositoryMockRecorder) GetByBoardID(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBoardID", reflect.TypeOf((*MockRepository)(nil).GetByBoardID), ctx, boardID)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*sprint.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*sprint.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetClosedByBoardID mocks base method.
func (m *MockRepository) GetClosedByBoardID(ctx context.Context, boardID uuid.UUID) ([]*sprint.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClosedByBoardID", ctx, boardID)
	ret0, _ := ret[0].([]*sprint.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClosedByBoardID indicates an expected call of GetClosedByBoardID.
func (mr *MockRepositoryMockRecorder) GetClosedByBoardID(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClosedByBoardID", reflect.TypeOf((*MockRepository)(nil).GetClosedByBoardID), ctx, boardID)
}

// GetClosedByBoardIDPaginated mocks base method.
func (m *MockRepository) GetClosedByBoardIDPaginated(ctx context.Context, boardID uuid.UUID, limit, offset int) ([]*sprint.Sprint, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClosedByBoardIDPaginated", ctx, boardID, limit, offset)
	ret0, _ := ret[0].([]*sprint.Sprint)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetClosedByBoardIDPaginated indicates an expected call of GetClosedByBoardIDPaginated.
func (mr *MockRepositoryMockRecorder) GetClosedByBoardIDPaginated(ctx, boardID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClosedByBoardIDPaginated", reflect.TypeOf((*MockRepository)(nil).GetClosedByBoardIDPaginated), ctx, boardID, limit, offset)
}

// GetFutureByBoardID mocks base method.
func (m *MockRepository) GetFutureByBoardID(ctx context.Context, boardID uuid.UUID) ([]*sprint.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFutureByBoardID", ctx, boardID)
	ret0, _ := ret[0].([]*sprint.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFutureByBoardID indicates an expected call of GetFutureByBoardID.
func (mr *MockRepositoryMockRecorder) GetFutureByBoardID(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFutureByBoardID", reflect.TypeOf((*MockRepository)(nil).GetFutureByBoardID), ctx, boardID)
}

// GetNextPosition mocks base method.
func (m *MockRepository) GetNextPosition(ctx context.Context, boardID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextPosition", ctx, boardID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextPosition indicates an expected call of GetNextPosition.
func (mr *MockRepositoryMockRecorder) GetNextPosition(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextPosition", reflect.TypeOf((*MockRepository)(nil).GetNextPosition), ctx, boardID)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *sprint.Sprint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1)
}
