// Code generated by MockGen. DO NOT EDIT.
// Source: permission_repository.go
//
// Generated by this command:
//
//	mockgen -source=permission_repository.go -destination=mocks/permission_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	permission "github.com/thatcatdev/kaimu/backend/internal/db/repositories/permission"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockRepository) GetAll(ctx context.Context) ([]*permission.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*permission.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepository)(nil).GetAll), ctx)
}

// GetByCode mocks base method.
func (m *MockRepository) GetByCode(ctx context.Context, code string) (*permission.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*permission.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockRepository)(nil).GetByCode), ctx, code)
}

// GetByCodes mocks base method.
func (m *MockRepository) GetByCodes(ctx context.Context, codes []string) ([]*permission.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCodes", ctx, codes)
	ret0, _ := ret[0].([]*permission.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCodes indicates an expected call of GetByCodes.
func (mr *MockRepositoryMockRecorder) GetByCodes(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCodes", reflect.TypeOf((*MockRepository)(nil).GetByCodes), ctx, codes)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*permission.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*permission.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetByResourceType mocks base method.
func (m *MockRepository) GetByResourceType(ctx context.Context, resourceType string) ([]*permission.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByResourceType", ctx, resourceType)
	ret0, _ := ret[0].([]*permission.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByResourceType indicates an expected call of GetByResourceType.
func (mr *MockRepositoryMockRecorder) GetByResourceType(ctx, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByResourceType", reflect.TypeOf((*MockRepository)(nil).GetByResourceType), ctx, resourceType)
}
